typography_spectrum: 0.25876
color:
  saturation: 0.04168090620078146
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors:
    - '#5fa893'
    - '#940031'
    - '#fae6b6'
    - '#be364e'
    - '#f1a600'
  lightness: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5071685
analytics:
  twitter: null
  google: null
  facebook: null
name: Amici Buffet
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Amici Buffet - Comfort Food! '
purpose: []
