name: Amici Buffet
favicon: null
layout_spectrum: 0.44273345335386693
typography_spectrum: 0.02299339370802045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.032175565138459206
  lightness: 0.7670910304877907
  saturation: 0.041680906200781465
  rhythmicContrast: 0.6818327726796269
purpose: []
