name: Amici Buffet
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25876
title: 'Comfort Food! Cozinha de Afeto para eventos! Amici Buffet por @reccruz'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#940031'
    - '#5fa893'
    - '#f1a600'
    - '#be364e'
  brandStrength: 0.032175565138459206
  lightness: 0.7670910304877907
  saturation: 0.041680906200781465
  rhythmicContrast: 0.6818327726796269
purpose: []
