name: Amici Buffet
favicon: null
layout_spectrum: 0.73957
typography_spectrum: 0.25876
title: 'Amici Buffet Comfort Food! Cozinha de Afeto para eventos! Amici Buffet por @reccruz'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5fa893'
    - '#940031'
    - '#fae6b6'
    - '#be364e'
    - '#f1a600'
  brandStrength: 0.5089605
  lightness: 0.7670910304877907
  saturation: 0.04168090620078146
  rhythmicContrast: 0.6818327726796269
purpose: []
